// The icons the console uses, by their design names (icon-<name> in the
// mockups → the lucide-react component). A named import per icon keeps the
// bundle to the icons in use; a new icon is one line here.

import {
  Activity,
  Archive,
  ArrowLeft,
  ArrowUp,
  ArrowUpRight,
  Bell,
  Bot,
  Brain,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleSlash,
  CircleStop,
  CircleX,
  ClockAlert,
  CloudOff,
  Copy,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  FileCode,
  FileText,
  Folder,
  FolderTree,
  GitFork,
  Hourglass,
  House,
  Inbox,
  Info,
  KeyRound,
  LayoutGrid,
  Link,
  Link2Off,
  LoaderCircle,
  LogOut,
  MapPinOff,
  MessageCircleQuestion,
  MessagesSquare,
  Pause,
  Pencil,
  Play,
  Plug,
  Plus,
  RefreshCw,
  Search,
  SlidersHorizontal,
  Terminal,
  Trash2,
  Upload,
  Wrench,
  X,
} from 'lucide-react';

export const ICONS = {
  activity: Activity,
  archive: Archive,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  bell: Bell,
  bot: Bot,
  brain: Brain,
  'calendar-clock': CalendarClock,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-slash': CircleSlash,
  'circle-stop': CircleStop,
  'circle-x': CircleX,
  'clock-alert': ClockAlert,
  'cloud-off': CloudOff,
  copy: Copy,
  database: Database,
  download: Download,
  ellipsis: Ellipsis,
  'external-link': ExternalLink,
  'file-code': FileCode,
  'file-text': FileText,
  folder: Folder,
  'folder-tree': FolderTree,
  'git-fork': GitFork,
  hourglass: Hourglass,
  house: House,
  inbox: Inbox,
  info: Info,
  'key-round': KeyRound,
  'layout-grid': LayoutGrid,
  link: Link,
  'link-2-off': Link2Off,
  'loader-circle': LoaderCircle,
  'log-out': LogOut,
  'map-pin-off': MapPinOff,
  'message-circle-question': MessageCircleQuestion,
  'messages-square': MessagesSquare,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  plus: Plus,
  'refresh-cw': RefreshCw,
  search: Search,
  'sliders-horizontal': SlidersHorizontal,
  terminal: Terminal,
  'trash-2': Trash2,
  upload: Upload,
  wrench: Wrench,
  x: X,
} as const;

export type IconName = keyof typeof ICONS;
