// The icons the console uses, by their design names (icon-<name> in the
// mockups → the lucide-react component). A named import per icon keeps the
// bundle to the icons in use; a new icon is one line here.

import {
  Activity,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bell,
  BellOff,
  BellRing,
  Bot,
  Brain,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleSlash,
  CircleStop,
  CircleX,
  Clock,
  ClockAlert,
  CloudOff,
  CloudUpload,
  Copy,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  EyeOff,
  FileArchive,
  FileCode,
  FileImage,
  FilePenLine,
  Files,
  FileSpreadsheet,
  FileText,
  FileType,
  Flag,
  Folder,
  FolderOpen,
  FolderTree,
  GitFork,
  Globe,
  History,
  Hourglass,
  House,
  Image,
  Inbox,
  Info,
  KeyRound,
  LayoutGrid,
  Link,
  Link2Off,
  ListTodo,
  LoaderCircle,
  Lock,
  LogOut,
  MapPinOff,
  MessageCircleQuestion,
  MessageSquareReply,
  MessagesSquare,
  Minimize2,
  OctagonX,
  Paperclip,
  Pause,
  Pencil,
  Pin,
  Play,
  Plug,
  Plus,
  RefreshCw,
  RotateCcw,
  Scissors,
  Search,
  ShieldX,
  SlidersHorizontal,
  SquareTerminal,
  Terminal,
  Trash2,
  TriangleAlert,
  Upload,
  Wrench,
  X,
} from 'lucide-react';

export const ICONS = {
  activity: Activity,
  archive: Archive,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  bell: Bell,
  'bell-off': BellOff,
  'bell-ring': BellRing,
  bot: Bot,
  brain: Brain,
  'calendar-clock': CalendarClock,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dashed': CircleDashed,
  'circle-slash': CircleSlash,
  'circle-stop': CircleStop,
  'circle-x': CircleX,
  clock: Clock,
  'clock-alert': ClockAlert,
  'cloud-off': CloudOff,
  // the design's icon-upload-cloud; lucide's current name
  'upload-cloud': CloudUpload,
  copy: Copy,
  database: Database,
  download: Download,
  ellipsis: Ellipsis,
  'external-link': ExternalLink,
  'eye-off': EyeOff,
  'file-archive': FileArchive,
  'file-code': FileCode,
  'file-image': FileImage,
  'file-pen-line': FilePenLine,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  'file-type': FileType,
  files: Files,
  flag: Flag,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-tree': FolderTree,
  'git-fork': GitFork,
  globe: Globe,
  history: History,
  hourglass: Hourglass,
  house: House,
  image: Image,
  inbox: Inbox,
  info: Info,
  'key-round': KeyRound,
  'layout-grid': LayoutGrid,
  link: Link,
  'link-2-off': Link2Off,
  'list-todo': ListTodo,
  'loader-circle': LoaderCircle,
  lock: Lock,
  'log-out': LogOut,
  'map-pin-off': MapPinOff,
  'message-circle-question': MessageCircleQuestion,
  'message-square-reply': MessageSquareReply,
  'messages-square': MessagesSquare,
  'minimize-2': Minimize2,
  'octagon-x': OctagonX,
  paperclip: Paperclip,
  pause: Pause,
  pencil: Pencil,
  pin: Pin,
  play: Play,
  plug: Plug,
  plus: Plus,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  scissors: Scissors,
  search: Search,
  'shield-x': ShieldX,
  'sliders-horizontal': SlidersHorizontal,
  'square-terminal': SquareTerminal,
  terminal: Terminal,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  upload: Upload,
  wrench: Wrench,
  x: X,
} as const;

export type IconName = keyof typeof ICONS;
