// The icons the console uses, by their design names (icon-<name> in the
// mockups → the lucide-react component). A named import per icon keeps the
// bundle to the icons in use; a new icon is one line here.

import {
  Activity,
  ArrowLeft,
  ArrowUp,
  Bell,
  Bot,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleX,
  ClockAlert,
  Copy,
  Download,
  Ellipsis,
  ExternalLink,
  FileCode,
  FileText,
  Folder,
  FolderTree,
  GitFork,
  House,
  Inbox,
  LayoutGrid,
  Link2Off,
  LoaderCircle,
  LogOut,
  MapPinOff,
  MessagesSquare,
  Pencil,
  Play,
  Plug,
  Plus,
  RefreshCw,
  Search,
  SlidersHorizontal,
  Terminal,
  Trash2,
  Upload,
  Wrench,
  X,
} from 'lucide-react';

export const ICONS = {
  activity: Activity,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  bell: Bell,
  bot: Bot,
  'calendar-clock': CalendarClock,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  'clock-alert': ClockAlert,
  copy: Copy,
  download: Download,
  ellipsis: Ellipsis,
  'external-link': ExternalLink,
  'file-code': FileCode,
  'file-text': FileText,
  folder: Folder,
  'folder-tree': FolderTree,
  'git-fork': GitFork,
  house: House,
  inbox: Inbox,
  'layout-grid': LayoutGrid,
  'link-2-off': Link2Off,
  'loader-circle': LoaderCircle,
  'log-out': LogOut,
  'map-pin-off': MapPinOff,
  'messages-square': MessagesSquare,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  plus: Plus,
  'refresh-cw': RefreshCw,
  search: Search,
  'sliders-horizontal': SlidersHorizontal,
  terminal: Terminal,
  'trash-2': Trash2,
  upload: Upload,
  wrench: Wrench,
  x: X,
} as const;

export type IconName = keyof typeof ICONS;
