// The HTML shell of an app: generated by the platform on every request of
// the app root (no-store) — the agent never writes index.html. Import map
// points the vendor set at /platform/vendor/*, entry/styles URLs are
// absolute, imports between app modules stay relative (the browser resolves
// them against the module URL).

import type { AppManifest } from './manifest.ts';

// The vendor set of the platform: bare specifier → bundle filename under
// /platform/vendor/. Extending the platform's capabilities for all apps =
// adding a pair here + a build target in build/server.js.
export const VENDOR_MODULES: Record<string, string> = {
  react: 'react.js',
  'react/jsx-runtime': 'react-jsx-runtime.js',
  'react-dom': 'react-dom.js',
  'react-dom/client': 'react-dom-client.js',
  '@tanstack/react-query': 'tanstack-react-query.js',
  'balabash/data': 'balabash-data.js',
};

// Internal chunks fetched by the facade modules themselves (not addressable
// via the import map, but served by the same vendor route).
export const VENDOR_INTERNAL_FILES = ['vendor-core.js'];

export type AppShellContext = {
  mode: 'owner' | 'public';
  apiBase: string;
  appPath?: string;
  slug?: string;
  refreshUrl?: string;
};

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// JSON destined for inline <script>: '<' escaped so '</script>' in any
// value cannot break out of the tag.
function scriptJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, '\\u003c');
}

export function renderAppShell(options: {
  manifest: AppManifest;
  /** Absolute URL base of the app's own files, no trailing slash. */
  appBase: string;
  /** URL base of the vendor bundles, no trailing slash. */
  vendorBase: string;
  /** Cache-busting version for vendor URLs. */
  vendorVersion: string;
  context: AppShellContext;
}): string {
  const { manifest, appBase, vendorBase, vendorVersion, context } = options;

  const imports: Record<string, string> = {};

  for (const [specifier, file] of Object.entries(VENDOR_MODULES)) {
    imports[specifier] = `${vendorBase}/${file}?v=${encodeURIComponent(vendorVersion)}`;
  }

  const styleLinks = manifest.styles
    .map(style => `  <link rel="stylesheet" href="${escapeHtml(`${appBase}/${style}`)}">`)
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(manifest.name)}</title>
  <script type="importmap">${scriptJson({ imports })}</script>
${styleLinks}
</head>
<body>
  <div id="root"></div>
  <script>window.__BALABASH_APP__ = ${scriptJson(context)};</script>
  <script type="module" src="${escapeHtml(`${appBase}/${manifest.entry}`)}"></script>
</body>
</html>
`;
}

// The readable stand-in for a broken passport (decision: never a 500 for a
// manifest problem — the author sees what to fix).
export function renderManifestErrorPage(appName: string, error: string): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>App manifest error</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 40rem; margin: 4rem auto; padding: 0 1rem; color: #1a1a1a; }
    code { background: #f4f4f4; padding: 0.1rem 0.3rem; border-radius: 4px; }
    pre { background: #f4f4f4; padding: 1rem; border-radius: 8px; white-space: pre-wrap; }
  </style>
</head>
<body>
  <h1>This app cannot start</h1>
  <p>The folder <code>${escapeHtml(appName)}</code> has a broken <code>balabash-app.json</code>:</p>
  <pre>${escapeHtml(error)}</pre>
  <p>Fix the manifest and refresh the page.</p>
</body>
</html>
`;
}
// The owner's catalog at /apps (step 5): server-rendered HTML from the core,
// one row per app folder found in the workspace — name, path, the owner run
// link, and the public link when published.
export type CatalogEntry = {
  path: string;
  name: string | null;
  description: string | null;
  manifestError: string | null;
  slug: string | null;
};

export function renderCatalogPage(entries: CatalogEntry[], appsDomain: string): string {
  const rows = entries
    .map(entry => {
      const title = entry.name ?? entry.path;
      const label = entry.manifestError
        ? '<span class="broken">broken manifest</span>'
        : entry.slug
          ? `<a href="https://${escapeHtml(appsDomain)}/${escapeHtml(entry.slug)}">public: /${escapeHtml(entry.slug)}</a>`
          : '<span class="private">not published</span>';

      return `  <li>
    <a class="app" href="/apps/${entry.path.split('/').map(encodeURIComponent).join('/')}"><strong>${escapeHtml(title)}</strong></a>
    <span class="path">${escapeHtml(entry.path)}</span> · ${label}
    ${entry.description ? `<div class="desc">${escapeHtml(entry.description)}</div>` : ''}
  </li>`;
    })
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Your apps</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 44rem; margin: 3rem auto; padding: 0 1rem; color: #1a1a1a; }
    ul { list-style: none; padding: 0; }
    li { padding: 0.9rem 0; border-bottom: 1px solid #eee; }
    .app { text-decoration: none; color: #0b57d0; font-size: 1.05rem; }
    .path { color: #888; font-size: 0.85rem; margin-left: 0.4rem; }
    .desc { color: #555; font-size: 0.9rem; margin-top: 0.25rem; }
    .private { color: #888; font-size: 0.9rem; }
    .broken { color: #b3261e; font-size: 0.9rem; }
  </style>
</head>
<body>
  <h1>Your apps</h1>
  ${entries.length ? `<ul>\n${rows}\n  </ul>` : '<p>No apps yet: an app is any workspace folder with a <code>balabash-app.json</code> manifest.</p>'}
</body>
</html>
`;
}
